#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  StopBumper,     sensorTouch)
#pragma config(Sensor, I2C_1,  RightBaseIEM,   sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  LeftBaseIEM,    sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_3,  RightElbowIEM,  sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_4,  LeftElbowIEM,   sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_5,  WristIEM,       sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_6,  SholderIEM,     sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           RightBase,     tmotorVex393HighSpeed, openLoop, encoder, encoderPort, I2C_1, 1000)
#pragma config(Motor,  port2,           LeftBase,      tmotorVex393HighSpeed, openLoop, encoder, encoderPort, I2C_5, 1000)
#pragma config(Motor,  port3,           RightElbow,    tmotorVex393HighSpeed, openLoop, encoder, encoderPort, I2C_2, 1000)
#pragma config(Motor,  port4,           LeftElbow,     tmotorVex393HighSpeed, openLoop, encoder, encoderPort, I2C_4, 1000)
#pragma config(Motor,  port5,           Wrist,         tmotorVex393HighSpeed, openLoop, encoder, encoderPort, I2C_3, 1000)
#pragma config(Motor,  port6,           Sholder,       tmotorVex393HighSpeed, openLoop, encoder, encoderPort, I2C_6, 1000)
#pragma config(Motor,  port7,           Claw,          tmotorVex269, openLoop)
#pragma config(Motor,  port9,           leftMotor,     tmotorVex393HighSpeed, openLoop, encoder, encoderPort, I2C_2, 1000)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task controle
{
	while(1==1)
	{
		motor[RightBase]=vexRT[Ch3];
		motor[LeftBase]=vexRT[Ch3];

	}
}


task main
{
	wait1Msec(2000);
	StartTask(controle);

	while(vexRT[Btn7D]==0&&SensorValue(StopBumper)==0)
	{
		motor[leftMotor] = -63;
	}
	StopAllTasks();
}
