#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  StopBumper,     sensorTouch)
#pragma config(Sensor, I2C_1,  RightBaseIEM,   sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  LeftBaseIEM,    sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_3,  RightElbowIEM,  sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_4,  LeftElbowIEM,   sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_5,  WristIEM,       sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_6,  SholderIEM,     sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port2,           LeftBase,      tmotorVex393HighSpeed, openLoop, encoder, encoderPort, I2C_5, 1000)
#pragma config(Motor,  port3,           Shoulder,      tmotorVex393HighSpeed, openLoop, encoder, encoderPort, I2C_6, 1000)
#pragma config(Motor,  port4,           Wrist,         tmotorVex393HighSpeed, openLoop, encoder, encoderPort, I2C_3, 1000)
#pragma config(Motor,  port5,           RightBase,     tmotorVex393HighSpeed, openLoop, reversed, encoder, encoderPort, I2C_1, 1000)
#pragma config(Motor,  port6,           Claw,          tmotorVex269, openLoop)
#pragma config(Motor,  port7,           LeftElbow,     tmotorVex393HighSpeed, openLoop, encoder, encoderPort, I2C_2, 1000)
#pragma config(Motor,  port8,           RightElbow,    tmotorVex393HighSpeed, openLoop, reversed, encoder, encoderPort, I2C_4, 1000)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task controle
{
	while(1==1)
	{
		if(vexRT[Btn5U])
		{
			motor[Shoulder]=125;
		}
		else{motor[Shoulder]=0;}
		if(vexRT[Btn5D])
		{
			motor[Shoulder]=-125;
		}
		else{motor[Shoulder]=0;}
		motor[Wrist]=vexRT[ch1];
		motor[LeftElbow]=vexRT[ch2];
		motor[RightElbow]=vexRT[ch2];
		motor[LeftBase]=vexRT[ch3]-vexRT[ch4];
		motor[RightBase]=vexRT[ch3]+vexRT[ch4];
	}
}


task main
{
	/*while(1==1)
	{
		if(vexRT[Btn8D])
		{
			motor[test]=40;
		}
		else{
			motor[test]=0;
		}
		if(vexRT[Btn8R])
		{
			motor[test]=-40;
		}
		else{
			motor[test]=0;
		}
	}*/
	wait1Msec(2000);
	StartTask(controle);

	while(vexRT[Btn7D]==0&&SensorValue(StopBumper)==0)
	{}
	StopAllTasks();
}
